#install_qiime.sub
#
universe = vanilla
# Name the log file:
log = install_qiime.log

# Name the files where standard output and error should be saved:
output = process.out
error = process.err

# If you wish to compile code, you'll need the below lines. 
#  Otherwise, LEAVE THEM OUT if you just want to interactively test!
+IsBuildJob = true
requirements = ( IsBuildSlot == true ) && (OpSysMajorVer =?= 6)

# Indicate all files that need to go into the interactive job session,
#  including any tar files that you prepared:
transfer_input_files = Python-2.7.13.tgz,ExpressionAnalysis-ea-utils-1.04.807-18-gbd148d4.tar.gz
transfer_output_files = qiime1.tar.gz,ea-utils.tar.gz

# It's still important to request enough computing resources. The below 
#  values are a good starting point, but consider your file sizes for an
#  estimate of "disk" and use any other information you might have
#  for "memory" and/or "cpus".

request_cpus = 1
request_memory = 8GB
request_disk = 2GB

queue
